apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "go-ethereum.name" . }}
    chart: {{ template "go-ethereum.chart" . }}
    heritage: {{ .Release.Service }}
    {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: go-ethereum

    {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
    {{- end }}
  name: {{ template "go-ethereum.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ template "go-ethereum.name" . }}
    {{- if .Values.useComponentLabel }}
      {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: go-ethereum
    {{- end }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.podAnnotationConfigChecksum }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.podAnnotationConfigChecksum }}
        checksum/config: {{ tpl (toYaml .Values) . | sha256sum }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ template "go-ethereum.name" . }}
        component: "{{ .Values.name }}"
        {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: go-ethereum
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "go-ethereum.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 300
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{  range .Values.arguments }}
            - {{ . | quote }}
          {{ end }}
          ports:
          {{- if .Values.service.enableHttpRpc }}
            - name: httprpc
              containerPort: {{ .Values.service.ports.httprpc }}
              protocol: TCP
          {{- end }}
          {{- if .Values.service.enableWsRpc }}
            - name: wsrpc
              containerPort: {{ .Values.service.ports.httprpc }}
              protocol: TCP
          {{- end }}
          {{- if .Values.service.enableNodeTcp }}
            - name: nodetcp
              containerPort: {{ .Values.service.ports.nodetcp }}
              protocol: TCP
          {{- end }}
          {{- if .Values.service.enableUdpDiscovery }}
            - name: udpdiscovery
              containerPort: {{ .Values.service.ports.udpdiscovery }}
              protocol: UDP
          {{- end }}
          {{- range $port := .Values.service.ports.tcp }}
            - name: "{{ $port }}-tcp"
              containerPort: {{ $port }}
              protocol: TCP
          {{- end }}
          {{- range $port := .Values.service.ports.udp }}
            - name: "{{ $port }}-udp"
              containerPort: {{ $port }}
              protocol: UDP
          {{- end }}
          volumeMounts:
          - mountPath: /data/
            name: data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.hostPath }}
        hostPath:
          path: {{.Values.persistence.hostPath}}
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "go-ethereum.fullname" . }}{{- end }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
