{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bitcoind.serviceAccountName" . }}
  labels:
{{ include "bitcoind.labels" . | indent 4 }}
{{- end -}}
