apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lnd.fullname" . }}
  namespace: {{ template "lnd.namespace" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.configurationFile | indent 2 }}
