{{- if .Values.ingress.rest.enabled -}}
{{- $ingressApiIsStable := eq (include "lnd.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "lnd.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "lnd.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "lnd.fullname" . -}}
{{- $servicePort := .Values.service.restPort -}}
{{- $ingressPath := .Values.ingress.rest.path -}}
{{- $ingressPathType := .Values.ingress.rest.pathType -}}
{{- $extraPaths := .Values.ingress.rest.extraPaths -}}
apiVersion: {{ include "lnd.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-rest
  namespace: {{ template "lnd.namespace" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
{{- if .Values.ingress.rest.labels }}
{{ toYaml .Values.ingress.rest.labels | indent 4 }}
{{- end }}
  {{- if .Values.ingress.rest.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.rest.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.rest.ingressClassName }}
  ingressClassName: {{ .Values.ingress.rest.ingressClassName }}
  {{- end -}}
{{- if .Values.ingress.rest.tls }}
  tls:
{{ tpl (toYaml .Values.ingress.rest.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .Values.ingress.rest.hosts  }}
  {{- range .Values.ingress.rest.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
            {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
  {{- end -}}
{{- end }}
