{{ if .Values.autoUnlock }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "lnd.fullname" . }}
  namespace: {{ template "lnd.namespace" . }}
data:
  wallet_password: {{ .Values.autoUnlockPassword | b64enc }}
{{ end }}
