{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "lnd.serviceAccountName" . }}
  namespace: {{ template "lnd.namespace" . }}
  labels:
{{ include "lnd.labels" . | indent 4 }}
{{- end -}}
