apiVersion: v1
kind: Service
metadata:
  name: {{ template "lnd.fullname" . }}
  namespace: {{ template "lnd.namespace" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: rest
      port: {{ .Values.service.restPort }}
      targetPort: rest
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: prometheus
      port: {{ .Values.service.prometheusPort }}
      targetPort: prometheus
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
