apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "btc-rpc-explorer.fullname" . }}
  labels:
    {{- include "btc-rpc-explorer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "btc-rpc-explorer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "btc-rpc-explorer.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "btc-rpc-explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /data/.env
              subPath: config
            - mountPath: /authcookie/
              name: authcookie
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        secret:
        {{ if .Values.existingConfigSecret }}
          secretName: {{ .Values.existingConfigSecret }}
        {{ else }}
          secretName: {{ .Release.Name }}-config-file
        {{ end}}
      - name: authcookie
      {{- if .Values.cookiePersistence.enabled }}
        {{- if .Values.cookiePersistence.hostPath }}
        hostPath:
          path: {{.Values.cookiePersistence.hostPath}}
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ .Values.cookiePersistence.existingClaim }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
