{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ckpool.serviceAccountName" . }}
  labels:
{{ include "ckpool.labels" . | indent 4 }}
{{- end -}}
