version: 2
updates:
  - package-ecosystem: "docker"
    directory: "charts/bitcoind"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "charts/btcpayserver"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "docker"
    directory: "charts/fulcrum"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "charts/lnd"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "charts/lndhub"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "charts/mempool"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "docker"
    directory: "charts/nbxplorer"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "charts/prometheus-bitcoind-exporter"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "charts/prometheus-bosminer-exporter"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "charts/thunderhub"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "charts/tor"
    schedule:
      interval: "daily"