{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tiddlywiki.serviceAccountName" . }}
  labels:
{{ include "tiddlywiki.labels" . | indent 4 }}
{{- end -}}
