{{- if .Values.ingress.rpc.enabled -}}
{{- $ingressApiIsStable := eq (include "c-lightning.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "c-lightning.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "c-lightning.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "c-lightning.fullname" . -}}
{{- $servicePort := .Values.service.rpcPort -}}
{{- $ingressPath := .Values.ingress.rpc.path -}}
{{- $ingressPathType := .Values.ingress.rpc.pathType -}}
{{- $extraPaths := .Values.ingress.rpc.extraPaths -}}
apiVersion: {{ include "c-lightning.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-rpc
  namespace: {{ template "c-lightning.namespace" . }}
  labels:
    {{- include "c-lightning.labels" . | nindent 4 }}
{{- if .Values.ingress.rpc.labels }}
{{ toYaml .Values.ingress.rpc.labels | indent 4 }}
{{- end }}
  {{- if .Values.ingress.rpc.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.rpc.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.rpc.ingressClassName }}
  ingressClassName: {{ .Values.ingress.rpc.ingressClassName }}
  {{- end -}}
{{- if .Values.ingress.rpc.tls }}
  tls:
{{ tpl (toYaml .Values.ingress.rpc.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .Values.ingress.rpc.hosts  }}
  {{- range .Values.ingress.rpc.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
            {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
  {{- end -}}
{{- end }}
