{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "c-lightning.serviceAccountName" . }}
  namespace: {{ template "c-lightning.namespace" . }}
  labels:
{{ include "c-lightning.labels" . | indent 4 }}
{{- end -}}
