apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "fulcrum.name" . }}
    chart: {{ template "fulcrum.chart" . }}
    heritage: {{ .Release.Service }}
    {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: fulcrum

    {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
    {{- end }}
  name: {{ template "fulcrum.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ template "fulcrum.name" . }}
    {{- if .Values.useComponentLabel }}
      {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: fulcrum
    {{- end }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.podAnnotationConfigChecksum }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.podAnnotationConfigChecksum }}
        checksum/config: {{ tpl (toYaml .Values) . | sha256sum }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ template "fulcrum.name" . }}
        component: "{{ .Values.name }}"
        {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: fulcrum
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "fulcrum.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 300
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/Fulcrum
          args:
          {{  range .Values.arguments }}
            - {{ . }}
          {{ end }}
          ports:
            - name: tcp
              containerPort: {{ .Values.service.ports.tcp }}
              protocol: TCP
            - name: ssl
              containerPort: {{ .Values.service.ports.ssl }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /data/config.toml
              subPath: config
            - mountPath: /data/
              name: data
            - mountPath: /authcookie/
              name: authcookie
            {{- if and .Values.certificate.enabled .Values.certificate.mountCertificate }}
            - name: tls
              mountPath: "/ssl/tls.crt"
              subPath: tls.crt
              readOnly: true
            - name: tls
              mountPath: "/ssl/tls.key"
              subPath: tls.key
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        secret:
        {{ if .Values.existingConfigSecret }}
          secretName: {{ .Values.existingConfigSecret }}
        {{ else }}
          secretName: {{ .Release.Name }}-config-file
        {{ end}}
      - name: data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.hostPath }}
        hostPath:
          path: {{.Values.persistence.hostPath}}
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "fulcrum.fullname" . }}{{- end }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      - name: authcookie
      {{- if .Values.cookiePersistence.enabled }}
        {{- if .Values.cookiePersistence.hostPath }}
        hostPath:
          path: {{.Values.cookiePersistence.hostPath}}
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ .Values.cookiePersistence.existingClaim }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if and .Values.certificate.enabled .Values.certificate.mountCertificate }}
      - name: tls
        secret:
          secretName: {{ template "fulcrum.fullname" . }}-secret
      {{- end }}