apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "btcpayserver.fullname" . }}-config
  labels:
  {{- include "btcpayserver.labels" . | nindent 4 }}
data:
  .cookie: |-
    {{ .Files.Get "config/.cookie" | b64enc }}
#   admin.macaroon: |-
#     {{ .Files.Get "config/admin.macaroon" | b64enc }}
#   tls.cert: |-
#     {{ .Files.Get "config/tls.cert" | b64enc }}
