
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
    app: {{ template "tor.name" . }}
    chart: {{ template "tor.chart" . }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
  name: {{ template "tor.fullname" . }}
spec:
{{- if not .Values.service.omitClusterIP }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ if eq "-" . }}""{{ else }}{{ . | quote }}{{ end }}
  {{- end }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
{{- if .Values.service.sessionAffinity }}
  sessionAffinity: "{{ .Values.service.sessionAffinity }}"
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.service.healthCheckNodePort }}
{{- end }}
  ports:
    {{- $setNodePorts := (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
    {{- if .Values.service.enableSocks }}
    - name: socks
      port: {{ .Values.service.ports.socks }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPorts.socks }}
      {{- if (and $setNodePorts (not (empty .Values.service.nodePorts.socks))) }}
      nodePort: {{ .Values.service.nodePorts.socks }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.enableController }}
    - name: controller
      port: {{ .Values.service.ports.controller }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPorts.controller }}
      {{- if (and $setNodePorts (not (empty .Values.service.nodePorts.controller))) }}
      nodePort: {{ .Values.service.nodePorts.controller }}
      {{- end }}
    {{- end }}
  {{- range $port := .Values.service.ports.tcp }}
    - name: "{{ $port }}-tcp"
      port: {{ $port }}
      protocol: TCP
      targetPort: "{{ $port }}-tcp"
     {{- if $.Values.service.nodePorts.tcp }}
      {{- if index $.Values.service.nodePorts.tcp $port }}
      nodePort: {{ index $.Values.service.nodePorts.tcp $port }}
      {{- end }}
     {{- end }}
  {{- end }}
  {{- range $port := .Values.service.ports.udp }}
    - name: "{{ $port }}-udp"
      port: {{ $port }}
      protocol: UDP
      targetPort: "{{ $port }}-udp"
     {{- if $.Values.service.nodePorts.udp }}
      {{- if index $.Values.service.nodePorts.udp $port }}
      nodePort: {{ index $.Values.service.nodePorts.udp $port }}
      {{- end }}
     {{- end }}
  {{- end }}
  selector:
    app: {{ template "tor.name" . }}
    {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: tor
  type: "{{ .Values.service.type }}"
{{- end }}
