
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-tplink-plug-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-tplink-plug-exporter.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-tplink-plug-exporter.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if not .Values.serviceMonitor.enabled }}
        prometheus.io/path: /
        prometheus.io/port: metrics
        prometheus.io/scrape: "true"
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "prometheus-tplink-plug-exporter.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - env:          
      {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
      {{- end }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "prometheus-tplink-plug-exporter.fullname" . }}
        args:
        - -metrics.listen-addr
        - ":{{ .Values.metricsListenPort }}"
        ports:
        - containerPort: {{ .Values.metricsListenPort }}
          protocol: TCP
        {{- with .Values.containerSecurityContext}}
        securityContext:
          {{- toYaml . | nindent 10}}
        {{- end}}
{{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "prometheus-tplink-plug-exporter.fullname" . }}
      serviceAccountName: {{ include "prometheus-tplink-plug-exporter.fullname" . }}
{{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
    {{- end }}
  {{- with .Values.securityContext }}
  securityContext:
{{- toYaml . | nindent 4 }}
{{- end }}
