{{- if .Values.ingress.enabled -}}
{{- if eq .Values.ingress.type "gke" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnd-lit.fullname" . }}-lb
  labels:
  {{- include "lnd-lit.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ include "lnd-lit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.config.lbport }}
  loadBalancerSourceRanges:
  - {{ .Values.config.allowrange }}
{{- end -}}

{{- else -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "lnd-lit.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "lnd-lit.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
