apiVersion: v1
name: wordpress
version: 1.0.1
appVersion: 5.4.0
description: Web publishing platform for building blogs and websites.
keywords:
  - wordpress
  - cms
  - blog
  - http
  - web
  - application
  - php
home: http://www.wordpress.com/
sources:
  - https://github.com/bboerst/helm-chart-sources/wordpress
maintainers:
  - name: Brian Boerst
    email: brian@boerst.com
engine: gotpl
