apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "datum-gateway.name" . }}
    chart: {{ template "datum-gateway.chart" . }}
    heritage: {{ .Release.Service }}
    {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: datum-gateway

    {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
    {{- end }}
  name: {{ template "datum-gateway.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ template "datum-gateway.name" . }}
    {{- if .Values.useComponentLabel }}
      {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: datum-gateway
    {{- end }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.podAnnotationConfigChecksum }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.podAnnotationConfigChecksum }}
        checksum/config: {{ tpl (toYaml .Values) . | sha256sum }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ template "datum-gateway.name" . }}
        component: "{{ .Values.name }}"
        {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: datum-gateway
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "datum-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 300
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{-  range .Values.arguments }}
            - {{ . }}
          {{- end }}
          ports:
            {{- range $port := .Values.service.ports.tcp }}
            - name: "{{ $port }}-tcp"
              containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/datum_gateway_config.json
              subPath: config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        secret:
        {{- if .Values.existingConfigSecret }}
          secretName: {{ .Values.existingConfigSecret }}
        {{ else }}
          secretName: {{ .Release.Name }}-config-file
        {{- end}}
