apiVersion: v2
appVersion: "v0.1.0"
description: BraiinsOS BOSMiner exporter to monitor bosminer metrics with Prometheus
engine: gotpl
name: prometheus-bosminer-exporter
version: 0.1.1
maintainers:
- email: brian@boerst.com
  name: bboerst
sources:
  - https://github.com/bboerst/helm-charts/
keywords:
- kubernetes
- apache
- bosminer
- exporter
- prometheus
- braiins
- braiinsos