---
name: bosminer-exporter

image:
  name: bboerst/bosminer-exporter
  tag: v0.1
  pullPolicy: IfNotPresent

annotations: {}

podAnnotations: {}

bosminerURL: http://bosminer
logLevel: info
logFormat: json

exporterPort: 8080

serviceAccount:
  create: true

serviceType: ClusterIP

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels: {}
  targetLabels: []

securityContext: {}

containerSecurityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
