{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "thunderhub.serviceAccountName" . }}
  labels:
{{ include "thunderhub.labels" . | indent 4 }}
{{- end -}}
