{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bitcoin-core.serviceAccountName" . }}
  labels:
{{ include "bitcoin-core.labels" . | indent 4 }}
{{- end -}}
