apiVersion: v1
kind: Secret
metadata:
  name: configjs-secret
  labels: {{- include "lndhub.labels" . | nindent 4}}
type: Opaque
stringData:
  config.js: |
    let config = {
      enableUpdateDescribeGraph: false,
      postRateLimit: 100,
      rateLimit: 200,
      forwardReserveFee: 0.01, // default 0.01
      intraHubFee: 0.003, // default 0.003
      bitcoind: {
        rpc: 'http://{{ .Values.config.bitcoind.user }}:{{ .Values.config.bitcoind.password }}@{{ .Values.config.bitcoind.host }}:{{ .Values.config.bitcoind.port }}/wallet/wallet.dat',
      },
      redis: {
        port: '{{ .Values.config.redis.port }}',
        host: '{{ .Values.config.redis.host }}',
        family: '{{ .Values.config.redis.family }}',
        password: '{{ .Values.global.redis.password }}',
        db: '{{ .Values.config.redis.db }}',
      },
      lnd: {
        url: '{{ .Values.config.lnd.url }}',
      },
    };

    if (process.env.CONFIG) {
      console.log('using config from env');
      config = JSON.parse(process.env.CONFIG);
    }

    module.exports = config;
