{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sabnzbd.serviceAccountName" . }}
  labels:
{{ include "sabnzbd.labels" . | indent 4 }}
{{- end -}}
