{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dydx-liquidator.serviceAccountName" . }}
  labels:
{{ include "dydx-liquidator.labels" . | indent 4 }}
{{- end -}}
