apiVersion: v1
data:
  config.js: {{default "" .Values.secrets.configjs | b64enc}}
kind: Secret
metadata:
  name: lndhub-config-js
  labels: {{- include "lndhub.labels" . | nindent 4}}
type: Opaque
---
apiVersion: v1
data:
  tls.cert: {{default "" .Values.secrets.tls_cert | b64enc}}
kind: Secret
metadata:
  name: lndhub-tls-cert
  labels: {{- include "lndhub.labels" . | nindent 4}}
type: Opaque
---
apiVersion: v1
data:
  admin.macaroon: {{default "" .Values.secrets.admin_macaroon}}
kind: Secret
metadata:
  name: lndhub-admin-macaroon
  labels: {{- include "lndhub.labels" . | nindent 4}}
type: Opaque
