{{- if .Values.backend.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "public-pool.fullname" . }}-backend
  labels:
    # Standard labels for the service.
    app: {{ template "public-pool.name" . }}-backend
    chart: {{ template "public-pool.chart" . }}
    component: "backend"
    heritage: {{ .Release.Service }}
  {{- if .Values.backend.service.annotations }}
  annotations:
{{ toYaml .Values.backend.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.backend.service.omitClusterIP }}
    {{- with .Values.backend.service.clusterIP }}
  clusterIP: {{ if eq "-" . }}""{{ else }}{{ . | quote }}{{ end }}
    {{- end }}
  {{- end }}
  {{- if .Values.backend.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.backend.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.backend.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.backend.service.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.backend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.backend.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.backend.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.backend.service.externalTrafficPolicy }}"
  {{- end }}
  {{- if .Values.backend.service.sessionAffinity }}
  sessionAffinity: "{{ .Values.backend.service.sessionAffinity }}"
  {{- end }}
  {{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.backend.service.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.backend.service.healthCheckNodePort }}
  {{- end }}
  ports:
    - name: "api"
      port: {{ .Values.backend.service.apiPort }}
      protocol: TCP
      targetPort: "api"
    - name: "stratum"
      port: {{ .Values.backend.service.stratumPort }}
      protocol: TCP
      targetPort: "stratum"
  selector:
    app: {{ template "public-pool.name" . }}-backend
    {{ .Values.backend.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: backend
  type: "{{ .Values.backend.service.type }}"
{{- end }}