{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "public-pool.serviceAccountName" . }}
  labels:
    {{- include "public-pool.labels" . | nindent 4 }}
{{- end -}}