{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rsyslog.serviceAccountName" . }}
  labels:
{{ include "rsyslog.labels" . | indent 4 }}
{{- end -}}
