apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsyslog.fullname" . }}
  labels:
{{ include "rsyslog.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - name: rsyslog
      port: 514
      targetPort: 514
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "rsyslog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
