apiVersion: v1
name: lnd
version: 0.1.0
appVersion: v0.17.0-beta
description: A golang implementation of a Lightning Network node
keywords:
  - lnd
  - bitcoin
home: https://github.com/lightningnetwork/lnd
