apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "lightning-terminal.fullname" . }}-credentials
  namespace: {{ template "lightning-terminal.namespace" . }}
data:
  admin.macaroon: {{ .Values.macaroon }}
  tls.cert: {{ .Values.certificate }}
