{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "lightning-terminal.serviceAccountName" . }}
  labels:
{{ include "lightning-terminal.labels" . | indent 4 }}
{{- end -}}
