
{{- if .Values.backend.service.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.backend.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.backend.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
{{- if .Values.backend.service.labels }}
{{ toYaml .Values.backend.service.labels | indent 4 }}
{{- end }}
    app: {{ template "mempool.name" . }}-backend
    chart: {{ template "mempool.chart" . }}
    component: "backend"
    heritage: {{ .Release.Service }}
  name: {{ template "mempool.fullname" . }}-backend
spec:
{{- if not .Values.backend.service.omitClusterIP }}
  {{- with .Values.backend.service.clusterIP }}
  clusterIP: {{ if eq "-" . }}""{{ else }}{{ . | quote }}{{ end }}
  {{- end }}
{{- end }}
{{- if .Values.backend.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.backend.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.backend.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.backend.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.backend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.backend.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.backend.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.backend.service.externalTrafficPolicy }}"
{{- end }}
{{- if .Values.backend.service.sessionAffinity }}
  sessionAffinity: "{{ .Values.backend.service.sessionAffinity }}"
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.backend.service.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.backend.service.healthCheckNodePort }}
{{- end }}
  ports:
    - name: "tcp"
      port: {{ .Values.backend.service.tcpPort }}
      protocol: TCP
      targetPort: "tcp"
  selector:
    app: {{ template "mempool.name" . }}-backend
    {{ .Values.backend.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: backend
  # type: "{{ .Values.backend.service.type }}"
{{- end }}
