{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mempool.serviceAccountName" . }}
  labels:
{{ include "mempool.labels" . | indent 4 }}
{{- end -}}
