{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "lnbits.serviceAccountName" . }}
  labels:
{{ include "lnbits.labels" . | indent 4 }}
{{- end -}}
