
{{- if .Values.service.enabled }}
{{- $servicePort := .Values.service.ports.tcp -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
    app: {{ template "thunderhub.name" . }}
    chart: {{ template "thunderhub.chart" . }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
  name: {{ template "thunderhub.fullname" . }}
spec:
{{- if not .Values.service.omitClusterIP }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ if eq "-" . }}""{{ else }}{{ . | quote }}{{ end }}
  {{- end }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
{{- if .Values.service.sessionAffinity }}
  sessionAffinity: "{{ .Values.service.sessionAffinity }}"
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.service.healthCheckNodePort }}
{{- end }}
  ports:
    - name: "{{ $servicePort }}-tcp"
      port: {{ $servicePort }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ template "thunderhub.name" . }}
    {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: thunderhub
  type: "{{ .Values.service.type }}"
{{- end }}
