apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "electrs.fullname" . }}
  labels:
    {{- include "electrs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "electrs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "electrs.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "electrs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ELECTRS_ELECTRUM_RPC_ADDR
            value: "$(MY_POD_IP):50001"
          - name: ELECTRS_MONITORING_ADDR
            value: "$(MY_POD_IP):4224"
          args:
          {{  range .Values.arguments }}
            - {{ . }}
          {{ end }}
          volumeMounts:
            - name: config
              mountPath: /data/config.toml
              subPath: config
            - mountPath: /data/
              name: data
            - mountPath: /authcookie/
              name: authcookie
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        secret:
        {{ if .Values.existingConfigSecret }}
          secretName: {{ .Values.existingConfigSecret }}
        {{ else }}
          secretName: {{ .Release.Name }}-config-file
        {{ end}}
      - name: data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.hostPath }}
        hostPath:
          path: {{.Values.persistence.hostPath}}
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "electrs.fullname" . }}{{- end }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      - name: authcookie
      {{- if .Values.cookiePersistence.enabled }}
        {{- if .Values.cookiePersistence.hostPath }}
        hostPath:
          path: {{.Values.cookiePersistence.hostPath}}
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ .Values.cookiePersistence.existingClaim }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}