{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "electrs.serviceAccountName" . }}
  labels:
{{ include "electrs.labels" . | nindent 4 }}
{{- end -}}
