apiVersion: v2
description: A Helm chart for mempool
name: mempool
version: 0.1.17
# renovate: image=mempool/frontend
appVersion: "v3.3.1"
dependencies:
- name: mariadb
  version: "26.2.0"
  repository: "https://charts.bitnami.com/bitnami"
