apiVersion: v2
description: A Helm chart for mempool
name: mempool
version: 0.1.6
# renovate: image=mempool/frontend
appVersion: "v3.0.0-dev8"
dependencies:
- name: mariadb
  version: "18.2.6"
  repository: "https://charts.bitnami.com/bitnami"
