apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ride-the-lightning.fullname" . }}
  namespace: {{ template "ride-the-lightning.namespace" . }}
  labels:
    app: {{ template "ride-the-lightning.name" . }}
    chart: {{ template "ride-the-lightning.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  RTL-Config.json: '{{ .Values.rtlConfig | toPrettyJson }}'