# Default values for lndhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  redis:
    password: sensitivepassword

config:
  redis:
    port: 6379
    host: lndhub-redis-headless
    family: 4
    db: 0

  bitcoind:
    host: bitcoind.bitcoin.svc.cluster.local
    port: 8332
    user: sensitiveuser
    password: sensitivepassword

  lnd:
    url: "lnd1-internal:10009"
    tls_cert: |
      -----BEGIN CERTIFICATE-----
      <lnd certificate>
      -----END CERTIFICATE-----
    
    # base64 encoded admin.macaroon
    admin_macaroon: lndmacaroooooooooooooooon

persistence:
  enabled: false
  ## Set storageClassName if you have no default defined
  #storageClassName: ""
  size: 1Gi

replicaCount: 1

image:
  repository: bluewalletorganization/lndhub
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  runAsUser: 1001
  runAsGroup: 1001

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: traefik-cert-manager
  hosts:
    - host: lndhub.domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: lndhub-tls
      hosts:
        - lndhub.domain

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
