apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "nutshell.name" . }}
    chart: {{ template "nutshell.chart" . }}
    heritage: {{ .Release.Service }}
    {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: nutshell

    {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
    {{- end }}
  name: {{ template "nutshell.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ template "nutshell.name" . }}
    {{- if .Values.useComponentLabel }}
      {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: nutshell
    {{- end }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.podAnnotationConfigChecksum }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.podAnnotationConfigChecksum }}
        checksum/config: {{ tpl (toYaml .Values) . | sha256sum }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ template "nutshell.name" . }}
        component: "{{ .Values.name }}"
        {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: nutshell
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "nutshell.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 300
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{  range .Values.command }}
            - {{ . }}
          {{ end }}
          env:
            - name: CASHU_DIR
              value: "/root/.cashu"
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.env.secret }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ template "nutshell.fullname" . }}
                key: {{ $key }}
          {{- end}}
          args:
          {{  range .Values.arguments }}
            - {{ . }}
          {{ end }}
          ports:
            {{- range $port := .Values.service.ports.tcp }}
            - name: "{{ $port }}-tcp"
              containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
            {{- range $port := .Values.service.ports.udp }}
            - name: "{{ $port }}-udp"
              containerPort: {{ $port }}
              protocol: UDP
            {{- end }}
          volumeMounts:
            - mountPath: /root/.cashu
              name: data
            {{- if and .Values.ssl.enabled .Values.ssl.mountCertificate }}
            - name: ssl
              mountPath: "/ssl/tls.crt"
              subPath: tls.crt
              readOnly: true
            - name: ssl
              mountPath: "/ssl/tls.key"
              subPath: tls.key
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.hostPath }}
        hostPath:
          path: {{.Values.persistence.hostPath}}
          type: Directory
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "nutshell.fullname" . }}{{- end }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      {{- if and .Values.ssl.enabled .Values.ssl.mountCertificate }}
      - name: ssl
        secret:
          secretName: {{ .Values.ssl.certificate.secretName }}
      {{- end }}