{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nutshell.serviceAccountName" . }}
  labels:
{{ include "nutshell.labels" . | nindent 4 }}
{{- end -}}
