name: Helm Lint

on:
  push:
    branches:
      - '**'  # This will match all branches
    paths:
      - '**/Chart.yaml'

jobs:
  helm_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.12.3'

    - name: Run Helm Lint on Changed Charts
      run: |
        chmod +x scripts/lint-changed-charts.sh
        ./scripts/lint-changed-charts.sh