name: Helm Lint

on: 
  pull_request:
    branches:
      - '**'

jobs:
  helm_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This is to fetch all history for all branches and tags

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.12.3'

    - name: Run Helm Lint on Changed Charts
      run: |
        chmod +x .github/scripts/lint-changed-charts.sh
        .github/scripts/lint-changed-charts.sh
