{{- range $i, $backend := .Values.backends }}
{{- $root := $ }}
{{- $backendName := (printf "backend-%s" $backend.name) | default (printf "backend-%d" $i) }}
{{- if $backend.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mempool.fullname" $root }}-{{ $backendName }}
  labels:
    app: {{ template "mempool.name" $root }}-{{ $backendName }}
    chart: {{ template "mempool.chart" $root }}
    component: "backend"
    heritage: {{ $root.Release.Service }}
  {{- if $backend.service.annotations }}
  annotations:
    {{- range $key, $value := $backend.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
{{- if not $backend.service.omitClusterIP }}
  {{- with $backend.service.clusterIP }}
  clusterIP: {{ if eq "-" . }}""{{ else }}{{ . | quote }}{{ end }}
  {{- end }}
{{- end }}
{{- if $backend.service.externalIPs }}
  externalIPs:
{{ toYaml $backend.service.externalIPs | indent 2 }}
{{- end }}
{{- if $backend.service.loadBalancerIP }}
  loadBalancerIP: "{{ $backend.service.loadBalancerIP }}"
{{- end }}
{{- if $backend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml $backend.service.loadBalancerSourceRanges | indent 2 }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" $root.Capabilities.KubeVersion.GitVersion) ($backend.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ $backend.service.externalTrafficPolicy }}"
{{- end }}
{{- if $backend.service.sessionAffinity }}
  sessionAffinity: "{{ $backend.service.sessionAffinity }}"
{{- end }}
{{- if and (semverCompare ">=1.7-0" $root.Capabilities.KubeVersion.GitVersion) ($backend.service.healthCheckNodePort) }}
  healthCheckNodePort: {{ $backend.service.healthCheckNodePort }}
{{- end }}
  ports:
    - name: "tcp"
      port: {{ $backend.service.tcpPort }}
      protocol: TCP
      targetPort: "tcp"
  selector:
    app: {{ template "mempool.name" $root }}-{{ $backendName }}
    {{ $backend.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: backend
{{- end }}
---
{{- end }}