apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "mempool.name" . }}-frontend
    chart: {{ template "mempool.chart" . }}
    heritage: {{ .Release.Service }}
    {{ .Values.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: frontend

    {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
    {{- end }}
  name: {{ template "mempool.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    type: {{ .Values.frontend.strategyType }}
  selector:
    matchLabels:
      app: {{ template "mempool.name" . }}-frontend
    {{- if .Values.frontend.useComponentLabel }}
      {{ .Values.frontend.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: frontend
    {{- end }}
  template:
    metadata:
      {{- if or .Values.frontend.podAnnotations .Values.frontend.podAnnotationConfigChecksum }}
      annotations:
      {{- range $key, $value := .Values.frontend.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.frontend.podAnnotationConfigChecksum }}
        checksum/config: {{ tpl (toYaml .Values) . | sha256sum }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ template "mempool.name" . }}-frontend
        component: "frontend"
        {{ .Values.frontend.componentLabelKeyOverride | default "app.kubernetes.io/component" }}: frontend
        {{- if .Values.frontend.podLabels }}
{{ toYaml .Values.frontend.podLabels | indent 8 }}
        {{- end }}
    spec:
    {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "mempool.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 300
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          args:
          {{  range .Values.frontend.arguments }}
            - {{ . }}
          {{ end }}
          env:
            - name: "BACKEND_MAINNET_HTTP_HOST"
              value: "{{ template "mempool.name" . }}-backend"
            - name: "FRONTEND_HTTP_PORT"
              value: "{{ .Values.frontend.service.tcpPort }}"
          {{- range $key, $val := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: "tcp"
              containerPort: {{ .Values.frontend.service.tcpPort }}
              protocol: TCP
          # livenessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - -c
          #     - grep -r mempool /proc/1/cmdline
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          # readinessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - -c
          #     - grep -r mempool /proc/1/cmdline
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          # volumeMounts:
          # - mountPath: /data/.bitcoin/
          #   name: data
          # - mountPath: /authcookie/
          #   name: authcookie
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      # volumes:
      # - name: data
      # {{- if .Values.frontend.persistence.enabled }}
      #   {{- if .Values.frontend.persistence.hostPath }}
      #   hostPath:
      #     path: {{.Values.frontend.persistence.hostPath}}
      #     type: Directory
      #   {{- else }}
      #   persistentVolumeClaim:
      #     claimName: {{ if .Values.frontend.persistence.existingClaim }}{{ .Values.frontend.persistence.existingClaim }}{{- else }}{{ template "mempool.fullname" . }}{{- end }}
      #   {{- end }}
      # {{- else }}
      #   emptyDir: {}
      # {{ end }}
